# Project: TestParallelPortLib
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"D:/Program Files/Dev-Cpp/lib" ../pjParallelPort.a  
INCS =  -I"D:/Program Files/Dev-Cpp/include"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjParallelPort" 
CXXINCS =  -I"D:/Program Files/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Program Files/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Program Files/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Program Files/Dev-Cpp/include/c++/3.4.2"  -I"D:/Program Files/Dev-Cpp/include"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjParallelPort" 
BIN  = TestParallelPortLib.exe
CXXFLAGS = $(CXXINCS)   -ansi
CFLAGS = $(INCS)   -ansi
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before TestParallelPortLib.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "TestParallelPortLib.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
