# Project: TestLibrary
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"D:/Program Files/Dev-Cpp/lib" -L"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjString" -L"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjPath" -L"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjTextReader" -L"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjTextWriter" -L"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjJpegFile"  ../pjPath/pjPath.a ../pjString/pjString.a ../pjTextReader/pjTextReader.a ../pjTextWriter/pjTextWriter.a ../pjJpegFile/pjJpegFile.a  
INCS =  -I"D:/Program Files/Dev-Cpp/include"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjPath"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjString"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjTextReader"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjTextWriter"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjJpegFile" 
CXXINCS =  -I"D:/Program Files/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"D:/Program Files/Dev-Cpp/include/c++/3.4.2/backward"  -I"D:/Program Files/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"D:/Program Files/Dev-Cpp/include/c++/3.4.2"  -I"D:/Program Files/Dev-Cpp/include"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjPath"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjString"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjTextReader"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjTextWriter"  -I"C:/Users/Administrator/Documents/GitHub/pjCLibs/pjJpegFile" 
BIN  = TestLibrary.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before TestLibrary.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "TestLibrary.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
